### ISSUE TITLE
정답 매칭 부분 작성

### ISSUE THREAD

**Issue by 142spp** [BE-team6/Bulls-and-Cows-team#2]
## Description

Bulls & Cows의 매칭 부분 작성. 
match 함수는 정답배열과 입력배열을 인자로 받아, 각각을 매치해 bull 과 cow 의 개수를 리스트형태로 반환한다.
bull 함수는 두개의 정수형 변수를 인자로 받아, 두 수가 같으면 true, 다르면 false를 반환한다.
cow 함수는 한개의 정수형 변수와 정수 리스트를 인자로 받아, 입력받은 수가 리스트 내에 있을경우 true를, 없을경우 false를 반환한다.

## Tasks

- [x] match 함수 작성
- [x] bull 함수 작성
- [x] cow 함수 작성
