### ISSUE TITLE
결과 출력부

### ISSUE THREAD

**Issue by zigimi** [BE-team6/Bulls-and-Cows-team#3]
## Description

Bulls and Cows의 결과를 전달 받아 출력

## Tasks

- [x] Bulls 결과 출력
- [x] Cows 결과 출력
- [x] 정답 시 'it's correct' 출력

## References

- [Bulls and Cows wikipedia] (https://en.wikipedia.org/wiki/Bulls_and_Cows)
