### ISSUE TITLE
사용자 입력부 작성 

### ISSUE THREAD

**Issue by chaee813** [BE-team6/Bulls-and-Cows-team#4]
## Description

Bulls and Cows 문제 해결을 위한 사용자 입력부를 작성하고자 합니다.

## Tasks

- [x] print required input format
- [x] get user input
- [x] handle improper input
 
## References 

- [simulation] (https://www.mathsisfun.com/games/bulls-and-cows.html)
